### ISSUE TITLE
Touch|dig spell is duplicating items.

### ISSUE THREAD

**Issue by NespinF** [Growlith1223/ArsMagica2#67] opened 2016-12-06 01:24 UTC
Ars Magica version: 1.5.0-9
Added to pack: FTB Presents Direwolf20 1.10 (version 1.1.0)
Other added mods: Roots v 0.207, NoMoreRecipieConflict 0.6, Tinker's Construct 1.10.2-2.6.0

The title is fairly self explanatory I think, but - today I decided to get started in Ars Magica, which is running on a small server I play with some friends! I crafted a fairly basic Touch|Dig spell to level up a bit, started using it... and realized that every time I used it to break one block, I was getting two blocks back.

**Comment by Growlith1223** [comment] 2016-12-06 01:26
duplicate of #55 and is also fixed, just no release download yet.

**Closed by Growlith1223** 2016-12-06 01:26 UTC

**Comment by NespinF** [comment] 2016-12-06 03:36
Whopse. Sorry for the duplicate then. First time using this system, managed to miss it.

**Comment by Growlith1223** [comment] 2016-12-06 13:18
lol no problem, it happens
