### ISSUE TITLE
Crash with mrcrayfish furniture

### ISSUE THREAD

**Issue by aroxy** [Growlith1223/ArsMagica2#313] opened 2017-04-10 16:05 UTC
The mod crash when i place a mirror from mrcrayfish furniture

___________________________________________________________________________
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 4/10/17 5:58 PM
Description: Unexpected error

java.lang.ClassCastException: com.mrcrayfish.furniture.entity.EntityMirror cannot be cast to net.minecraft.entity.EntityLivingBase
	at am2.particles.ParticleRenderer.render(ParticleRenderer.java:156)
	at am2.particles.ParticleRenderer.onRenderWorldLast(ParticleRenderer.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_9_ParticleRenderer_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:166)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1400)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at com.mrcrayfish.furniture.render.tileentity.MirrorRenderer.onTick(MirrorRenderer.java:159)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_100_MirrorRenderer_onTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:350)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1074)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at am2.particles.ParticleRenderer.render(ParticleRenderer.java:156)
	at am2.particles.ParticleRenderer.onRenderWorldLast(ParticleRenderer.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_9_ParticleRenderer_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:166)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1400)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at com.mrcrayfish.furniture.render.tileentity.MirrorRenderer.onTick(MirrorRenderer.java:159)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_100_MirrorRenderer_onTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Aroxygames'/1551, l='MpServer', x=285.81, y=67.00, z=123.08]]
	Chunk stats: MultiplayerChunkCache: 547, 547
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (237,64,182), Chunk: (at 13,4,6 in 14,11; contains blocks 224,0,176 to 239,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2889 game time, 2889 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 156 total; [EntityBat['Bat'/3330, l='MpServer', x=228.44, y=40.00, z=137.75], EntityCreeper['Creeper'/3589, l='MpServer', x=207.56, y=43.88, z=166.83], EntityCreeper['Creeper'/3590, l='MpServer', x=212.50, y=43.00, z=166.50], EntityBat['Bat'/1798, l='MpServer', x=268.75, y=43.11, z=162.48], EntityCreeper['Creeper'/3080, l='MpServer', x=272.50, y=47.00, z=162.50], EntityZombie['Zombie'/3082, l='MpServer', x=290.35, y=47.00, z=159.35], EntityCreeper['Creeper'/4619, l='MpServer', x=282.50, y=36.00, z=137.50], EntityZombie['Zombie'/3085, l='MpServer', x=287.50, y=47.00, z=160.50], EntityItem['item.tile.gravel'/1550, l='MpServer', x=253.44, y=40.00, z=177.87], EntityPlayerSP['Aroxygames'/1551, l='MpServer', x=285.81, y=67.00, z=123.08], EntitySkeleton['Skeleton'/3859, l='MpServer', x=226.50, y=44.00, z=157.50], EntitySkeleton['Skeleton'/3860, l='MpServer', x=231.50, y=44.00, z=157.50], EntitySkeleton['Skeleton'/5145, l='MpServer', x=260.50, y=44.00, z=161.50], EntitySkeleton['Skeleton'/5146, l='MpServer', x=259.50, y=44.00, z=159.50], EntityCreeper['Creeper'/3611, l='MpServer', x=272.50, y=47.00, z=168.50], EntityZombie['Zombie'/5147, l='MpServer', x=260.50, y=44.00, z=156.50], EntitySpider['Spider'/4380, l='MpServer', x=226.50, y=40.00, z=194.50], EntityZombie['Zombie'/4894, l='MpServer', x=316.50, y=64.00, z=154.76], EntityCreeper['Creeper'/4130, l='MpServer', x=211.50, y=43.00, z=162.50], EntityCreeper['Creeper'/4132, l='MpServer', x=209.50, y=43.00, z=162.50], EntityItem['item.item.seeds'/2852, l='MpServer', x=282.03, y=63.00, z=168.29], EntitySkeleton['Skeleton'/4133, l='MpServer', x=211.50, y=43.00, z=164.50], EntityBat['Bat'/4389, l='MpServer', x=262.07, y=37.63, z=120.10], EntityZombie['Zombie'/4134, l='MpServer', x=216.26, y=43.00, z=157.48], EntitySkeleton['Skeleton'/2861, l='MpServer', x=230.70, y=36.00, z=176.47], EntitySkeleton['Skeleton'/4910, l='MpServer', x=256.50, y=31.00, z=44.50], EntityItem['item.item.seeds'/2863, l='MpServer', x=285.19, y=63.00, z=170.28], EntityZombie['Zombie'/5167, l='MpServer', x=269.44, y=12.00, z=161.18], EntityZombie['Zombie'/5168, l='MpServer', x=272.50, y=15.00, z=164.50], EntityCreeper['Creeper'/5169, l='MpServer', x=270.50, y=15.00, z=165.31], EntityCreeper['Creeper'/5170, l='MpServer', x=270.50, y=15.00, z=164.30], EntityCreeper['Creeper'/5172, l='MpServer', x=286.50, y=50.00, z=168.50], EntityBat['Bat'/3637, l='MpServer', x=266.26, y=50.18, z=156.64], EntityWitch['Witch'/5173, l='MpServer', x=288.50, y=50.00, z=169.50], EntityWitch['Witch'/5174, l='MpServer', x=291.50, y=50.00, z=167.50], EntitySkeleton['Skeleton'/3899, l='MpServer', x=303.50, y=63.00, z=176.50], EntitySpider['Spider'/4159, l='MpServer', x=215.50, y=43.00, z=148.50], EntityCreeper['Creeper'/4160, l='MpServer', x=209.59, y=42.00, z=145.83], EntityCreeper['Creeper'/4164, l='MpServer', x=269.50, y=47.00, z=173.50], EntityCreeper['Creeper'/4165, l='MpServer', x=268.50, y=47.00, z=174.50], EntitySheep['Sheep'/81, l='MpServer', x=208.79, y=63.00, z=167.50], EntitySheep['Sheep'/82, l='MpServer', x=209.79, y=66.00, z=149.80], EntityItem['item.tile.doublePlant.rose'/2642, l='MpServer', x=275.51, y=64.00, z=136.99], EntitySheep['Sheep'/83, l='MpServer', x=217.48, y=63.00, z=158.77], EntityItem['item.tile.torch'/88, l='MpServer', x=235.46, y=40.00, z=97.13], EntityItem['item.tile.torch'/89, l='MpServer', x=245.30, y=42.00, z=101.83], EntityItem['item.tile.torch'/90, l='MpServer', x=235.38, y=40.00, z=113.06], EntityMinecartChest['Minecart with Chest'/91, l='MpServer', x=234.50, y=40.06, z=125.50], EntityItem['item.item.seeds'/2907, l='MpServer', x=316.46, y=68.00, z=127.95], EntityMirror['entity.cfm.Mirror.name'/5211, l='MpServer', x=287.50, y=67.50, z=120.07], EntityBat['Bat'/3932, l='MpServer', x=266.25, y=42.97, z=151.13], EntityItem['item.tile.torch'/92, l='MpServer', x=235.54, y=39.00, z=120.70], EntityMinecartChest['Minecart with Chest'/93, l='MpServer', x=241.50, y=40.06, z=135.50], EntitySkeleton['Skeleton'/3422, l='MpServer', x=265.50, y=42.00, z=147.50], EntityItem['item.tile.torch'/94, l='MpServer', x=235.13, y=35.00, z=128.95], EntityItem['item.tile.torch'/95, l='MpServer', x=242.17, y=40.00, z=139.13], EntityItem['item.tile.torch'/96, l='MpServer', x=241.88, y=40.00, z=149.22], EntityItem['item.tile.rail'/97, l='MpServer', x=243.77, y=40.00, z=139.13], EntitySkeleton['Skeleton'/3426, l='MpServer', x=268.50, y=42.00, z=149.50], EntitySkeleton['Skeleton'/4965, l='MpServer', x=300.50, y=40.00, z=140.50], EntityItem['item.tile.rail'/102, l='MpServer', x=242.24, y=40.00, z=139.13], EntitySquid['Squid'/2924, l='MpServer', x=236.60, y=57.00, z=162.87], EntityItem['item.tile.rail'/108, l='MpServer', x=241.39, y=40.00, z=149.22], EntitySquid['Squid'/2925, l='MpServer', x=241.01, y=62.00, z=147.36], EntitySkeleton['Skeleton'/4461, l='MpServer', x=267.50, y=37.00, z=130.50], EntityItem['item.item.seeds'/2413, l='MpServer', x=244.54, y=63.00, z=135.07], EntitySquid['Squid'/2926, l='MpServer', x=230.40, y=57.00, z=160.40], EntityItem['item.tile.rail'/110, l='MpServer', x=239.93, y=40.00, z=151.30], EntityBat['Bat'/4463, l='MpServer', x=240.96, y=33.03, z=189.42], EntityItem['item.item.seeds'/2415, l='MpServer', x=247.50, y=67.00, z=113.95], EntityItem['item.tile.rail'/112, l='MpServer', x=234.76, y=40.00, z=141.05], EntityItem['item.tile.rail'/113, l='MpServer', x=235.79, y=40.00, z=139.23], EntityZombie['Zombie'/1906, l='MpServer', x=272.50, y=47.00, z=157.50], EntityCreeper['Creeper'/3186, l='MpServer', x=246.50, y=41.00, z=140.50], EntityBat['Bat'/4466, l='MpServer', x=240.26, y=33.63, z=190.47], EntityItem['item.tile.sapling.oak'/3442, l='MpServer', x=332.51, y=76.00, z=157.88], EntityFlicker['entity.arsmagica2.Flicker.name'/4468, l='MpServer', x=291.54, y=87.47, z=138.77], EntityFlicker['entity.arsmagica2.Flicker.name'/4724, l='MpServer', x=255.25, y=74.00, z=73.16], EntityPig['Pig'/122, l='MpServer', x=263.50, y=70.00, z=82.50], EntityEnderman['Enderman'/4986, l='MpServer', x=271.48, y=23.00, z=52.56], EntityPig['Pig'/123, l='MpServer', x=256.72, y=69.00, z=88.33], EntityPig['Pig'/124, l='MpServer', x=257.50, y=70.00, z=82.50], EntityPig['Pig'/125, l='MpServer', x=258.50, y=70.00, z=81.50], EntityItem['item.tile.torch'/126, l='MpServer', x=254.62, y=40.00, z=170.88], EntityMinecartChest['Minecart with Chest'/127, l='MpServer', x=278.50, y=41.06, z=122.50], EntityItem['item.tile.torch'/128, l='MpServer', x=265.40, y=37.00, z=127.21], EntityBat['Bat'/4992, l='MpServer', x=307.36, y=40.57, z=114.49], EntityZombie['Zombie'/4225, l='MpServer', x=254.50, y=44.00, z=161.50], EntityItem['item.item.string'/129, l='MpServer', x=259.71, y=37.00, z=119.62], EntityZombie['Zombie'/4226, l='MpServer', x=254.50, y=44.00, z=160.50], EntityItem['item.item.string'/130, l='MpServer', x=260.77, y=37.00, z=120.88], EntityFlicker['entity.arsmagica2.Flicker.name'/4994, l='MpServer', x=227.56, y=11.94, z=115.43], EntityZombie['Zombie'/3203, l='MpServer', x=269.50, y=43.00, z=172.50], EntityZombie['Zombie'/4227, l='MpServer', x=254.50, y=44.00, z=160.50], EntityBat['Bat'/4995, l='MpServer', x=229.54, y=11.62, z=113.75], EntityItem['item.item.string'/132, l='MpServer', x=260.87, y=37.00, z=118.59], EntitySpider['Spider'/3205, l='MpServer', x=268.50, y=43.00, z=171.50], EntityItem['item.tile.rail'/133, l='MpServer', x=273.23, y=37.00, z=119.49], EntityItem['item.tile.rail'/135, l='MpServer', x=274.46, y=37.00, z=118.94], EntityItem['item.tile.rail'/136, l='MpServer', x=267.88, y=37.00, z=124.20], EntityItem['item.tile.rail'/138, l='MpServer', x=265.74, y=37.00, z=127.22], EntityZombie['Zombie'/2699, l='MpServer', x=232.44, y=34.00, z=175.70], EntityItem['item.tile.rail'/139, l='MpServer', x=266.55, y=37.00, z=127.78], EntityItem['item.tile.rail'/655, l='MpServer', x=250.49, y=43.00, z=151.90], EntityPig['Pig'/143, l='MpServer', x=290.25, y=69.00, z=48.73], EntityPig['Pig'/144, l='MpServer', x=297.19, y=70.00, z=54.26], EntityPig['Pig'/145, l='MpServer', x=291.87, y=69.00, z=49.79], EntityItem['item.tile.torch'/147, l='MpServer', x=284.40, y=41.00, z=112.82], EntityItem['item.tile.torch'/148, l='MpServer', x=287.60, y=41.00, z=114.19], EntityPig['Pig'/149, l='MpServer', x=293.50, y=68.00, z=116.50], EntityItem['item.item.seeds'/2454, l='MpServer', x=281.68, y=63.00, z=166.99], EntityPig['Pig'/150, l='MpServer', x=295.50, y=68.00, z=117.50], EntityPig['Pig'/151, l='MpServer', x=291.50, y=68.00, z=114.50], EntityPig['Pig'/152, l='MpServer', x=288.50, y=68.00, z=116.50], EntityItem['item.item.seeds'/2456, l='MpServer', x=261.94, y=70.00, z=87.14], EntityItem['item.tile.torch'/153, l='MpServer', x=284.13, y=43.00, z=162.23], EntityMinecartChest['Minecart with Chest'/154, l='MpServer', x=292.50, y=43.06, z=162.50], EntityZombie['Zombie'/3484, l='MpServer', x=265.50, y=47.00, z=165.50], EntitySkeleton['Skeleton'/5020, l='MpServer', x=291.50, y=37.00, z=116.50], EntityZombie['Zombie'/3485, l='MpServer', x=266.50, y=47.00, z=162.50], EntityCreeper['Creeper'/5021, l='MpServer', x=212.50, y=42.00, z=145.50], EntityZombie['Zombie'/3486, l='MpServer', x=268.50, y=47.00, z=168.50], EntityItem['item.tile.torch'/159, l='MpServer', x=309.13, y=39.00, z=131.88], EntitySkeleton['Skeleton'/3489, l='MpServer', x=270.48, y=52.03, z=135.07], EntityItem['item.tile.arsmagica2:witchwood_sapling'/2470, l='MpServer', x=236.13, y=76.00, z=145.59], EntityFlicker['entity.arsmagica2.Flicker.name'/4775, l='MpServer', x=311.61, y=75.75, z=141.79], EntityPig['Pig'/178, l='MpServer', x=339.50, y=73.00, z=48.50], EntityPig['Pig'/179, l='MpServer', x=339.50, y=73.00, z=48.50], EntityMinecartChest['Minecart with Chest'/182, l='MpServer', x=329.50, y=39.06, z=128.50], EntityItem['item.tile.torch'/183, l='MpServer', x=331.13, y=39.00, z=122.05], EntityCow['Cow'/184, l='MpServer', x=342.43, y=66.00, z=155.40], EntityCow['Cow'/185, l='MpServer', x=350.23, y=67.00, z=155.52], EntityCow['Cow'/186, l='MpServer', x=342.50, y=65.00, z=159.50], EntityCow['Cow'/187, l='MpServer', x=342.50, y=65.00, z=159.50], EntityPig['Pig'/194, l='MpServer', x=347.50, y=65.00, z=176.50], EntityPig['Pig'/195, l='MpServer', x=344.50, y=64.00, z=176.50], EntityPig['Pig'/196, l='MpServer', x=336.75, y=64.00, z=185.33], EntityItem['item.tile.arsmagica2:witchwood_sapling'/2756, l='MpServer', x=232.88, y=66.00, z=137.00], EntityPig['Pig'/197, l='MpServer', x=340.69, y=64.00, z=175.50], EntityPig['Pig'/4293, l='MpServer', x=294.50, y=70.00, z=46.50], EntityCreeper['Creeper'/2502, l='MpServer', x=270.50, y=47.00, z=162.50], EntityCow['Cow'/198, l='MpServer', x=345.50, y=63.00, z=190.50], EntityPig['Pig'/4294, l='MpServer', x=341.50, y=73.00, z=46.50], EntityCow['Cow'/199, l='MpServer', x=352.23, y=63.00, z=191.50], EntityPig['Pig'/4295, l='MpServer', x=343.50, y=73.00, z=47.50], EntityItem['item.tile.flower1.dandelion'/200, l='MpServer', x=335.92, y=64.00, z=180.85], EntityZombie['Zombie'/4822, l='MpServer', x=220.50, y=42.00, z=177.50], EntityBat['Bat'/2777, l='MpServer', x=252.25, y=41.10, z=171.13], EntityCreeper['Creeper'/2266, l='MpServer', x=272.50, y=47.00, z=161.11], EntityFlicker['entity.arsmagica2.Flicker.name'/3802, l='MpServer', x=259.16, y=72.63, z=127.87], EntityItem['item.item.seeds'/2522, l='MpServer', x=241.91, y=67.00, z=73.70], EntityBat['Bat'/4321, l='MpServer', x=253.51, y=35.12, z=131.96], EntityCreeper['Creeper'/4844, l='MpServer', x=308.48, y=58.00, z=199.79], EntityZombie['Zombie'/4845, l='MpServer', x=229.50, y=44.00, z=153.50], EntityCreeper['Creeper'/4846, l='MpServer', x=229.50, y=44.00, z=154.50], EntityBat['Bat'/3068, l='MpServer', x=223.13, y=42.10, z=139.52]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2574630944 bytes (2455 MB) / 3299868672 bytes (3147 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9216m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAAAA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAAAA	arsmagica2{1.5.018} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHIJAAAAAA	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHIJAAAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
	UCHIJAAAAAA	mcmultipart{1.3.0_87} [MCMultiPart] (MCMultiPart-experimental-2.0.0_88-universal.jar) 
	Loaded coremods (and transformers): 
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  am2.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.92' Renderer: 'GeForce GTX 760/PCIe/SSE2'
	Launched Version: forge-12.18.3.2281
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.5.0 NVIDIA 378.92, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz

**Comment by TheIcyOne** [comment] 2017-04-10 16:29
Duplicate of #304, fixed by #305

**Comment by Growlith1223** [comment] 2017-05-20 17:02
Closing this until further notice.

**Closed as completed by Growlith1223** 2017-05-20 17:02 UTC
