### ISSUE TITLE
1.5.0-11: Mana Shield is named Mana Blast in compendium entry, and the real mana blast is not localized 

### ISSUE THREAD

**Issue by ProfHugo** [Growlith1223/ArsMagica2#93] opened 2016-12-10 06:15 UTC
It appears to only be wrong in the component list.

What's supposed to be mana shield
![2016-12-09_22 11 41](https://cloud.githubusercontent.com/assets/23370942/21071668/b01ffc58-be5c-11e6-8cdb-5eb21e7e3362.png)

when you clicked on it
![2016-12-09_22 12 51](https://cloud.githubusercontent.com/assets/23370942/21071672/c5bcb862-be5c-11e6-9137-af47f730fd55.png)

the real mana blast page
![2016-12-09_22 14 08](https://cloud.githubusercontent.com/assets/23370942/21071674/d94e8888-be5c-11e6-82ba-d151748310e2.png)

![2016-12-09_22 14 11](https://cloud.githubusercontent.com/assets/23370942/21071675/daf78590-be5c-11e6-8c87-cd6a2e43c95b.png)

**Comment by Growlith1223** [comment] 2016-12-10 06:38
dupe of #72 and is already fixed

**Closed as completed by Growlith1223** 2016-12-10 06:38 UTC
