### ISSUE TITLE
Digging spell multiplying any block

### ISSUE THREAD

**Issue by pirone2** [Growlith1223/ArsMagica2#44] opened 2016-11-16 22:52 UTC
A simple spell with the touch shape and dig component is for some reason giving me and the other player on the server two of any block it is "digging" on the 1.5.0-9 release. This means that anyone can easily multiply wool, wood, ores, even diamond blocks, thankfully usable blocks like enchantment tables cant' be dug since you activate them inseat of casting the dig spell, but maybe a projectile dig spell might duplicate those too.
Note that this didn't happen in the 1.5.0-6 version.

**Comment by TheIcyOne** [comment] 2016-11-17 00:18
Duplicate of #42, should be fixed in next version.

**Comment by Growlith1223** [comment] 2016-11-17 01:28
already fixed in the github code. will probably release a new version in a few days!

**Closed by Growlith1223** 2016-11-17 01:28 UTC
