### ISSUE TITLE
Disarm Spell not working.

### ISSUE THREAD

**Issue by xenxero1** [Growlith1223/ArsMagica2#234] opened 2017-02-15 02:35 UTC
Tested using the Projectile || Disarm spell.

Upon landing the spell, no event takes place. Players do not drop their held items, and neither mage type will drop the Affinity Tome: None (And yes, I know only dark mages are supposed to drop them). The spell did however work once on a skeleton.

Am2: -17b

**Comment by TheIcyOne** [comment] 2017-02-15 11:02
Mobs issue is a duplicate of #58, fixed by #120 which is not a part of latest release, as far as I can tell,  both mage types currently have disarm effects disabled and a fix is incoming for players.

**Comment by xenxero1** [comment] 2017-02-15 13:59
By having disarm disabled, does that mean theres a config I can toggle? Or is that just something I have to wait until its hardcoded true?
Can we get this tagged Code Complete? I'd assign it myself if I had the proper role.

**Comment by xenxero1** [comment] 2017-02-15 14:02
Can we get this tagged Code Complete? I'd assign it myself if I had the proper role.

**Comment by TheIcyOne** [comment] 2017-02-15 14:20
In current release versions, it is hard-coded disabled due to an issue with the dark mages being disarmed.

**Closed as completed** 2017-02-18 21:42 UTC

**Comment by TheIcyOne** [comment] 2017-02-19 11:11
Note that #235 also fixed disarming dark mages.
