### ISSUE TITLE
1.5.0-11 Fire Guardian crashs Minecraft

### ISSUE THREAD

**Issue by garnichtpascal** [Growlith1223/ArsMagica2#111] opened 2016-12-19 16:43 UTC
I spawned the fire guardin and then my minecraft crashed. When I join on the server my minecraft crashs instant.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-11.jar)
  LoadingPlugin (Bloodmoon-MC1.10.2-1.5.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  IC2core (industrialcraft-2-2.6.128-ex110.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  LoadingPlugin (Quark-r1.1-66.jar)
  LoadingHook (Mekanism-1.10.2-9.2.1.295.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 19.12.16 17:41
Description: Ticking entity

java.lang.IllegalStateException: Base Tag must exist
	at am2.utils.NBTUtils.addTag(NBTUtils.java:60)
	at am2.utils.NBTUtils.getAM2Tag(NBTUtils.java:21)
	at am2.utils.SpellUtils.getModifiersForStage(SpellUtils.java:661)
	at am2.utils.SpellUtils.modifierIsPresent(SpellUtils.java:111)
	at am2.entity.EntitySpellEffect.rainOfFireUpdate(EntitySpellEffect.java:267)
	at am2.entity.EntitySpellEffect.func_70071_h_(EntitySpellEffect.java:141)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at am2.utils.NBTUtils.addTag(NBTUtils.java:60)
	at am2.utils.NBTUtils.getAM2Tag(NBTUtils.java:21)
	at am2.utils.SpellUtils.getModifiersForStage(SpellUtils.java:661)
	at am2.utils.SpellUtils.modifierIsPresent(SpellUtils.java:111)
	at am2.entity.EntitySpellEffect.rainOfFireUpdate(EntitySpellEffect.java:267)
	at am2.entity.EntitySpellEffect.func_70071_h_(EntitySpellEffect.java:141)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: arsmagica2.SpellEffect (am2.entity.EntitySpellEffect)
	Entity ID: 5763
	Entity Name: entity.arsmagica2.SpellEffect.name
	Entity's Exact location: -209,93, 64,00, 257,73
	Entity's Block location: World: (-210,64,257), Chunk: (at 14,4,1 in -14,16; contains blocks -224,0,256 to -209,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0,00, 0,00, 0,00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)

**Comment by Growlith1223** [comment] 2016-12-20 05:46
duplicate of #95 
Please look to see if the issue has been posted!
it's been fixed.

**Closed as completed by Growlith1223** 2016-12-20 05:46 UTC
