### ISSUE TITLE
Ars Magica 2 1.5.0-15 block FPS lag

### ISSUE THREAD

**Issue by lordchubz** [Growlith1223/ArsMagica2#149] opened 2017-01-09 15:05 UTC
On my custom mod pack running forge - 12.18.3.2185

Getting severe FPS lag where AM2 blocks are placed.  I tested and recreated in nether as well.  Definitely not all blocks but here's a list that I've tested with, it compounds too, it just gets worse with the more machines I have down.  I did try a good bit of blocks but not all of them.  Wasn't there an animation API in 1.7.10?  Is that still a thing?

EDIT:  Also made a new test world with just Forge 12.18.3.2185 and AM2 same version in title.  Having same issue, upgraded Forge to 12.18.3.2202 with same issue.

Retrogen isn't on either.

Blocks:
Arcane Deconstructor
Aracne Reconstructor
Astral Barrier
Calefactor
Crafting Altar
Draining Well
Essence Refiner
Everstone
Flicker Habitat
Imbuement Table
Obelisk
Seer Stone
Slipstream Generator
Summoner

**Comment by EPIICTHUNDERCAT** [comment] 2017-01-13 08:54
#20

**Comment by Growlith1223** [comment] 2017-01-17 05:22
duplicate of #20, closing

**Closed as completed by Growlith1223** 2017-01-17 05:22 UTC
Labels: bug
