### ISSUE TITLE
1.50-11 F3 information GUI messed up

### ISSUE THREAD

**Issue by alpha8196** [Growlith1223/ArsMagica2#105] opened 2016-12-16 12:56 UTC
back again,with yet another minor issue, still on forge 2185
[https://imgur.com/a/9ZBcK](url)

**Comment by ProfHugo** [comment] 2016-12-16 18:29
This is pretty much a dupe of #97 and it got fixed a while ago

**Comment by alpha8196** [comment] 2016-12-16 18:50
oops,sorry
by the way,how's the update that's said to come a few hours ago?

**Closed as completed** 2016-12-17 07:26 UTC
